# Generated by Django 2.0.8 on 2018-08-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadpage',
            name='body',
        ),
    ]
